### ISSUE TITLE
Steam Workshop Port

### ISSUE THREAD

**Issue by NBKRedSpy** [bo0tzz/voidchests#1]
I had a user ask if this mod will be ported to Steam Workshop and updated to support the latest game, so I figured I would forward the request.

**Comment by bo0tzz** [comment]
Hey :) Unfortunately I won't be able to get around to doing that anytime soon. If anybody else wants to they have my full blessing though.

**Comment by NBKRedSpy** [comment]
OK, it looks to be pretty straight forward so I'll just fork and port it.
There was a user with a disability that said it really helped them.

**Comment by NBKRedSpy** [comment]
Actually, I'm not sure on the correct etiquette.  I figured a fork was the most correct since I would be "maintaining" it, but should I just push here instead?

**Comment by NBKRedSpy** [comment]
https://github.com/NBKRedSpy/Stacklands-voidchests
https://steamcommunity.com/sharedfiles/filedetails/?id=3011778140

Thanks for permission.  I'm sure he will appreciate it.

**Comment by bo0tzz** [comment]
A fork is perfectly fine, but if you prefer to merge back into this repo and keep up with it here that works as well, up to you. Thanks for picking this up!
